#FROM alpine:latest

#RUN apk update && apk upgrade && apk add --no-cache libc6-compat && apk add --no-cache libstdc++ && apk add --no-cache libgcc && apk add --no-cache curl && apk add --no-cache procps && apk add --no-cache g++ && apk add --no-cache make

#--- For Nginx image ---
#FROM nginx:1.27.0-alpine-slim
#---

#--- For Debian development ----
#FROM debian:11
#RUN apt update && apt -y upgrade && apt -y install build-essential && apt -y install manpages-dev
#--- 

#--- For Alpine development ----
FROM alpine:latest
RUN apk update && apk upgrade && apk add bash build-base gcc linux-headers
RUN apk add sqlite-dev

COPY compile.sh ./
ENTRYPOINT ["./compile.sh"]
#---

# Установим gcc, mske и пр
#RUN yum groupinstall "Development Tools" -y
# Установим ps
#RUN yum install -y procps


